apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: shippingstore
  namespace: default
spec:
  type: state.mongodb
  version: v1
  metadata:
    - name: host
      value: localhost:27017
    - name: database
      value: state
    - name: collection
      value: shippingstate
